version: "3.9"

services:
  postgres:
    container_name: tenders_db

    image: postgres:latest
    environment:
      - POSTGRES_DB=tenders
      - POSTGRES_USER=helio
      - POSTGRES_PASSWORD=passme

    volumes:
      - ./docker_db:/docker-entrypoint-initdb.d/

    ports:
      - "5433:5432"



volumes:
  postgres_storage: