env: "local"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 30s

postgres:
  postgres_conn: "postgres://helio:passme@localhost:5433/tenders?sslmode=disable"
  # postgres_jdbc_url: "jdbc:postgresql://localhost:5432/dbname"
  postgres_username: "helio"
  postgres_password: "passme"
  postgres_host: "localhost"
  postgres_port: 5433
  postgres_database: "tenders"